hub.json
This is to add Fivetran's new Mailchimp package to dbt hub.
cc: @clrcrl
=> Add Fivetran's Mailchimp package to hub

hub.json
@clrcrl The salesforce package is ready for the hub.
=> Add Fivetran's Salesforce package

hub.json
Created a new package to collect useful, Snowflake-specific macros.
Feedback is welcome on docs or on the code :)
=> Add snowflake-utils

source/index.html.erb
yooooo did not think this would work :)
=> Order packages alphabetically

data/packages/fishtown-analytics/audit_helper/versions/0.2.0.json, data/packages/fishtown-analytics/codegen/versions/0.2.0.json
audit-helper: https://github.com/fishtown-analytics/dbt-audit-helper/blob/0.2.0/packages.yml
codegen: https://github.com/fishtown-analytics/dbt-codegen/blob/0.2.0/packages.yml
=> Manually fix upper bounds

data/packages/rudderlabs/rudder_customer_journey_analysis/index.json, data/packages/rudderlabs/rudder_customer_journey_analysis/versions/1.0.0.json, data/packages/rudderlabs/rudder_customer_journey_analysis/versions/1.0.1.json, data/packages/rudderlabs/rudder_events_registry/index.json, data/packages/rudderlabs/rudder_events_registry/versions/1.0.0.json, data/packages/rudderlabs/rudder_events_registry/versions/1.0.1.json, data/packages/rudderlabs/rudder_id_resolution/index.json, data/packages/rudderlabs/rudder_id_resolution/versions/1.0.0.json, data/packages/rudderlabs/rudder_id_resolution/versions/1.0.1.json, data/packages/rudderlabs/rudder_sessionization/index.json, data/packages/rudderlabs/rudder_sessionization/versions/1.0.0.json, data/packages/rudderlabs/rudder_sessionization/versions/1.0.1.json
Re-opening from:
- https://github.com/fishtown-analytics/hub.getdbt.com/pull/240
- https://github.com/fishtown-analytics/hub.getdbt.com/pull/241
- https://github.com/fishtown-analytics/hub.getdbt.com/pull/242
- https://github.com/fishtown-analytics/hub.getdbt.com/pull/243
=> Merge 4 RudderStack packages

.github/labeler.yml, .github/workflows/auto-merge.yml, .github/workflows/label.yml
Uses a couple of popular GitHub Actions to chain together a workflow that 1) auto labels any PR on a package with "automerge" and 2) merges the PR if it is "ready". Needs to be merged in before I can test it tho 🙃
=> Setup auto-merge for automatic Hubcap PRs 

data/packages/fivetran/fivetran_utils/versions/v0.1.0.json
Based on: https://github.com/fivetran/dbt_fivetran_utils/blob/v0.1.0/packages.yml#L1-L3
Related to https://github.com/dbt-labs/hubcap/issues/44
=> Manually add packages for fivetran_utils v0.1.0

data/packages/fivetran/fivetran_utils/versions/v0.1.1.json
Follow-up to #673
See: https://github.com/fivetran/dbt_fivetran_utils/blob/v0.1.1/packages.yml
FYI @drewbanin: This is going to keep being a problem until we fix https://github.com/dbt-labs/hubcap/issues/44
=> Manually fix fivetran_utils packages

data/packages/calogica/dbt_expectations/versions/0.4.0.json
=> Add dbt-expectations 0.4.0

data/packages/tailsdotcom/dbt_artifacts/index.json, source/_nav.erb
=> Update _nav.erb to fix GH button

data/packages/tailsdotcom/dbt_artifacts/index.json, source/_nav.erb
Reverts dbt-labs/hub.getdbt.com#703
Reverting because automerge isn't behaving like it should -- it's not waiting for all tests to complete
=> Revert "Update _nav.erb to fix GH button"

data/packages/tailsdotcom/dbt_artifacts/index.json
This is breaking builds. Fix by adding the right sem ver. Automerge check should fail because write has been disabled for now
=> Fix builds by fixing sem ver

data/packages/jitsucom/dbt-jitsu/index.json, data/packages/jitsucom/dbt-jitsu/versions/0.1.0.json
Addressing [bug report here](https://getdbt.slack.com/archives/CU4MRJ7QB/p1627628258001600) while long term fix is in the works
=> Add initial dbt-jitsu release

data/packages/tailsdotcom/dbt_artifacts/index.json
See: https://github.com/dbt-labs/hubcap/pull/87
cc @NiallRees
=> Redirect dbt-artifacts from tails to bklyn

data/packages/snowplow/snowplow_mobile/versions/0.5.2.json, data/packages/snowplow/snowplow_web/versions/0.9.1.json
Resolves https://github.com/dbt-labs/hub.getdbt.com/issues/1790
=> Add require_dbt_version to active packages currently missing it

data/blocklist.json, data/packages/dbt-labs/segment/index.json, data/packages/fishtown-analytics/segment/index.json
Follow up from https://github.com/dbt-labs/hubcap/pull/242
=> Swap to Fleetio/segment

data/blocklist.json, data/packages/Datavault-UK/dbtvault/index.json
dbtvault rebrand to AutomateDV
Corresponding hubcap PR: https://github.com/dbt-labs/hubcap/pull/258
=>  Rename dbtvault to AutomateDV

.gitignore, vercel.json
[Asana task](https://app.asana.com/0/1200099998847559/1205508339405074/)
On Vercel, URLs are case-sensitive - `/About` is different than `/about` for example. This wasn’t an issue on Netlify as Netlify didn’t care if the url had capital letters or not.
This adds redirects for packages which have uppercase names, to redirect all lowercase URLs to the appropriate casing.
To test, verify this URLs which has all lowercase, redirects appropriate to the correct casing:
https://hub-getdbt-com-git-add-redirects-for-capitalize-e036c5-dbt-labs.vercel.app/datavault-uk/automate_dv/0.7.3
https://hub-getdbt-com-git-add-redirects-for-capitalize-e036c5-dbt-labs.vercel.app/gjmcclintock/dbt_tld/latest
https://hub-getdbt-com-git-add-redirects-for-capitalize-e036c5-dbt-labs.vercel.app/saras-daton/amazonvendor …
=> Add redirects for capitalized packages

.github/CODEOWNERS, .github/workflows/deploy.yml
Adds a deploy workflow to github actions
=> add deploy workflow

source/disclaimer.html.erb
update email to the main one that is used in all our material.
=> update support email
