dbt-labs/hub.getdbt.com

- config.rb
- source/_hidden.erb
- source/layouts/layout.html.erb
- source/package.template.html.erb
Closes #186
Example outdated package:
- https://5eb96ea0c8c5770007d9891f--flamboyant-mcclintock-92ba2d.netlify.app/fishtown-analytics/dbt_utils/0.2.5/
Example blacklisted package (b/c we changed the name):
- https://5eb96ea0c8c5770007d9891f--flamboyant-mcclintock-92ba2d.netlify.app/fishtown-analytics/dbt-utils/latest/
Example latest package:
- https://5eb96ea0c8c5770007d9891f--flamboyant-mcclintock-92ba2d.netlify.app/fishtown-analytics/dbt_utils/latest/
All of these pages with "outdated" banners are tagged with a `noindex` meta tag, so they should hopefully not be indexed by search engines going forwards
> Do not index and warn for outdated packages

- config.rb
- data/blocklist.json
- data/featured.json
- source/index.html.erb
- source/layouts/layout.html.erb
Happy to use another term here instead of "blocklist" if there's one that's more appropriate.
BTW, we might need to update the blocklist to include org name, especially if we deprecate the packages that share a package name with a fivetran package
> Update featured & use blocklist terminology

- source/index.html.erb
This change helps disambiguate different packages with the same name by organization
> Adds org namespaces in package list

- config.rb
- data/blocklist.json
- source/index.html.erb
- source/layouts/layout.html.erb
First, I attempted to make this org-specific so I wouldn't accidentally blocklist a Fivetran package.
Then, I added  new packages to the list.
**Before:**
**After:**
> Deprecate additional fishtown packages

- data/blocklist.json
For some reason, the `fivetran/stripe` package is no longer working. This is a temp fix 🤞
> Remove stripe from blocklist

- data/blocklist.json
Reverts fishtown-analytics/hub.getdbt.com#256
This was not the problem
> Revert "Remove stripe from blocklist"

- config.rb
- source/index.html.erb
This PR has the potential to break `dbt deps` invocations in prod. Do not merge this until we have tested running `dbt deps` against this branch deploy.
Changes:
- Make the package index consider the package author + package name. Previous versions of the hub site built an index based solely on package name. This meant that when two packages were provided with the same name (ie. `stripe`), only _one_ of those packages would actually have pages built for the Hub UI and API.
> qualify package names in internal index

- data/packages/fishtown-analytics/logging/index.json
- data/packages/fishtown-analytics/logging/versions/0.4.2.json
0.4.2 was released last October, and it was never picked up by HubCap: https://github.com/fishtown-analytics/dbt-event-logging/releases/tag/0.4.2
I manually updated the info in `0.4.2.json`, including the `sha1` hashing, based on the [logic here](https://github.com/fishtown-analytics/hubcap/blob/6060cfb0dfd594675b2916c7940a5d16782bbd70/hubcap.py#L84-L100). Is there a better way to have manually triggered the automated updater?
> Bump fishtown-analytics/logging [missed by HubCap]

- data/packages/dbt-labs/audit_helper/index.json
- data/packages/dbt-labs/audit_helper/versions/0.0.1.json
- data/packages/dbt-labs/audit_helper/versions/0.0.2.json
- data/packages/dbt-labs/audit_helper/versions/0.0.6.json
- data/packages/dbt-labs/audit_helper/versions/0.1.0.json
- data/packages/dbt-labs/audit_helper/versions/0.2.0.json
- data/packages/dbt-labs/audit_helper/versions/0.3.0.json
- data/packages/dbt-labs/audit_helper/versions/v0.0.3.json
- data/packages/dbt-labs/audit_helper/versions/v0.0.4.json
- data/packages/dbt-labs/audit_helper/versions/v0.0.5.json
- data/packages/dbt-labs/dbt_external_tables/index.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.1.0.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.1.1.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.1.2.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.1.3.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.2.0.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.3.0.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.3.1.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.3.2.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.4.0.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.5.0.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.6.0.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.6.1.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.6.2.json
- data/packages/dbt-labs/dbt_external_tables/versions/0.6.3.json
Hubcap missed these, I'm not sure why. I just copied from `fishtown-analytics/audit_helper` + `dbt-labs/dbt_external_tables`, and did find+replace for `fishtown-analytics` --> `dbt-labs`
> Add dbt-labs/audit_helper + dbt-labs/dbt_external_tables

- data/packages/fivetran/fivetran_utils/versions/v0.2.0.json
Follow-up to #686
See: https://github.com/fivetran/dbt_fivetran_utils/blob/v0.2.0/packages.yml
dbt-labs/hubcap#44 is still a problem
> Fix packages for fivetran_utils 0.2.0

- data/packages/fivetran/fivetran_utils/versions/v0.2.1.json
Follow-up to #689
See: https://github.com/fivetran/dbt_fivetran_utils/blob/v0.2.1/packages.yml
dbt-labs/hubcap#44 is still a problem
> Fix packages for fivetran_utils 0.2.1

- data/packages/fivetran/fivetran_utils/versions/v0.2.3.json
Follow-up to #699
See: https://github.com/fivetran/dbt_fivetran_utils/blob/v0.2.3/packages.yml
Actually missing for v0.2.2, weirdly: https://github.com/fivetran/dbt_fivetran_utils/tree/v0.2.2. Looks like the release was removed after the fact, but the tag is still there.
dbt-labs/hubcap#44 is still a problem
> Fix packages for fivetran-utils 0.2.3

- .github/workflows/auto-merge.yml
Automerge was not respecting Netlify build status before merging. Repo settings have been changed to protect the master branch -- Netlify deploys must succeed before automerge kicks in
> Turn automerge back on

- source/_nav.erb
Landing page banner currently looks like this following rename: 
Expected behavior:
> Update _nav.erb to fix GH star button

- data/packages/calogica/dbt_expectations/index.json
- data/packages/calogica/dbt_expectations/versions/0.4.1.json
Addresses https://github.com/dbt-labs/hub.getdbt.com/issues/755 while long term fix is in the works.
> Manually bump dbt expectations 0.4.1

- README.md
On later Mac versions it may be necessary to upgrade Ruby to at least 2.7 and run some additional configuration before running bundle install. This PR just adds a note to the README with a link to a thread with troubleshooting advice.
> Add reference to docs for troubleshooting ruby version issues 

- .github/workflows/auto-merge.yml
If a ready for review or work in progress label is present, automerge will fail. This way a PR can wait on reviews before merge
> Make auto-merge less annoying

- source/package.template.html.erb
There's a margin if you view the redirect banner on a small screen. This PR fixes this. 
Before: 
After:
> Fix padding on mobile

- .github/labeler.yml
Reverts dbt-labs/hub.getdbt.com#830
Things are looking good as I manually merge the PRs. `dbt deps` keeps finding and successfully installing package after package, which is a great sign.
Since the major deployment, I found one little bug that was quickly fixed over in [hubcap](https://github.com/dbt-labs/hubcap/pull/63).
> Revert "Temporary disable of this workflow."

- data/packages/dbt-labs/dbt_utils/versions/0.7.2.json
Saw an issue where packages config was getting set to null - this should be '[]' instead
> fix empty package config causing error when running deps on 0.7.2

- README.md
- config.rb
1️⃣  Closes #118
1 line solution that comes from a few iterations of experimentation. This address the the problem idiomatically and in a well-defined way.
I heartily invite you to inspect the behavior for yourself on the Netlify deploy :)
2️⃣  Documentation additions
Added documentation for how I got local development working on Big Sur.
Redirect to latest version of a package, with no duplicating of uri "space" (cf. search space). This solution in particular requires no intervention on the web server layer yet keeps uris sensible for SEO tracking and such.
Here's a trivial solution: "Just" add this code in `config.rb` (the equivalent in Middleman apps to the more ubiquitous, Rails-style `routes.rb`):
```ruby
proxy "/#{package_name}/",
'/package.template.html',
:content_type => …
```
> Use middleman redirect to send package uris to preexisting latest version uris.

- .github/workflows/rebase-pull-requests.yml
As I understand it, there is an issue with the current Hubcap -> hub.getdbt.com workflow where if multiple releases are tracked at the same time, only one of the PRs that gets created can be auto-merged because the subsequent PRs no longer have a clean merge into `master`.
This change implements a new GitHub Actions workflow to rebase any open PR each time a commit to master happens. As a result, it should sequentially update each PR, which in turn will sequentially get merges into `master`. This means that multiple releases can all happen within the same hour and people won't have to push one release every hour.
> Add workflow to automatically rebase PRs

- data/featured.json
Closes #1455 
- elevates discoverability of the `codegen` package
- we recommend that most teams should use the `codegen` package
- the community should use [official package(s) from Snowplow](https://hub.getdbt.com/snowplow/) instead of the [dbt Labs version](https://hub.getdbt.com/dbt-labs/snowplow/latest/) (which we should deprecate)
- maintains only 3 featured packages
> Reprioritize Featured Packages to include the `codegen` package

- data/blocklist.json
- data/packages/elementary-data/elementary_data_reliability/index.json
Closes #1460
Combine the two package listings for elementary-data into one by following [this](https://github.com/dbt-labs/hub.getdbt.com/pull/876/files) example.
(If the namespace was being renamed, we'd use [this](https://github.com/dbt-labs/hub.getdbt.com/pull/1220/files)  example instead.)
Put the change to the top of the blocklist instead of the bottom (reverse chronological).
Rationale: JSON doesn't supply trailing commas for the last item in a list, so chronological additions end up with longer diffs.
So we get this diff:
Instead of one like this:
> Redirect to new name of package by elementary-data

- source/layouts/layout.html.erb
- source/package.template.html.erb
Resolves #1718
Simple and easy fix 😄
> Fix capitilization for GitHub

- source/author.template.html.erb
Resolves #1675
Here's how an alphabetized version looks:
> Alphabetize packages on each org-specific page (same as the home page)

- source/stylesheets/main.css.scss
Related to #1583
Update to fix how summary blocks are displayed. The issue was that a stylesheet from the old `www.getdbt.com` was overriding `summary.display` to `block`.
The following screenshots are from https://hub.getdbt.com/dbt-labs/dbt_project_evaluator/0.1.0/ , next to "Using This Package".
This is still not 100% perfect, especially when special formatting is done within the `details` tag, but based on my troubleshooting, this is a limitation of [kramdown](https://github.com/gettalong/kramdown), the MD renderer used in `middleman`. ([Here is a demo](https://kramdown-sandbox.herokuapp.com/) of kramdown if someone wants to try specific behavior). But I feel that this is still a pretty big improvement compare to the current behavior.
> Fix the display of summary blocks

- source/layouts/layout.html.erb
- source/package.template.html.erb
Clearly nerd-sniped on this one 😄  but I wasn't happy enough with the poor rendering in the `details` block after my previous fix.
After further investigation, I realized that the rendering of MD is not done by `middleman` itself but by `marked.js` as a JS script. After updating `marked.js` to a much more recent version the rendering looks much better!
It now looks identical to GitHub!
This will be very helpful for dbt_project_evaluator as we can now use and abuse `summary`/`details` and still get it rendering well on the Hub.
> Use updated version of marked.js

- source/stylesheets/main.css.scss
Last update from my side related to #1583
This change puts the different badges on a single row instead of one below each other. 
They are still not centered but fixing the alignment will require much more work as the style is defined as "inherited" in the old css files.
> Put Github badges on one row

- CONTRIBUTING.md
Continues #1788 (bulk of the work in #1782).
Assuming the necessary Ruby environment is all set up, the install+run instructions are now as simple as:
> Install dependencies with `bundler` and run with middleman:
> ```bash
> bundle install
> bundle exec middleman serve --port 4567
> ```
> Remove git submodules from installation instructions

- source/package.template.html.erb
Fixes #165
The new logic shows the dbt version required. I tested it with:
- removing `require_dbt_version` for a package JSON (in case it's not getting populated for some reason)
- `require_dbt_version` being an empty array (defined but empty)
- `require_dbt_version` being an array (most of the cases, with a lower and upper bound)
- `require_dbt_version` being a string
Keen for any feedback on how we should show it.
> Show dbt version required

- config.rb
- source/_nav.erb
- source/package.template.html.erb
POC related to #1724 but with a different approach. Feel free to just close it if we don't want to implement it.
The link to dbt-core's repo in GitHub is removed from the main page but it is replaced by links to individual packages, showing the number of stars for each package.
In that case, the key difference between the link in the nav bar and the link in the body is that the nav bar points to the main/master branch when the body points to the actual branch the user has selected.
> Show package link to Github and number of stars in nav bar

- source/package.template.html.erb
Fixes #1458 
Leverages the snippets from [this SO page](https://stackoverflow.com/questions/33289799/version-sort-with-alphas-betas-etc-in-ruby)
> Fix sorting semver

- data/blocklist.json
Per discussion in https://github.com/dbt-labs/hubcap/pull/203
There were two scopes of work discussed:
1. Renaming the "core" package to "the_tuva_project" within the Hub
1. Archiving the "medicare_cclf_connector" and "medicare_claims_connector" packages
This PR covers the only latter (and not the former).
> Archive tuva-health medicare connector package(s)

- .github/workflows/auto-merge.yml
- .github/workflows/rebase-pull-requests.yml
Please merge this update today! [node 12 support dropping tomorrow](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/) and these version updates to Github Actions get ahead of that. Resolves RELENG-144
> update used gh actions ahead of node12 deprecation

- CONTRIBUTING.md
This updates the preview URL to the correct Netlify site name within the `CONTRIBUTING.md` file.
Note - This will need to be updated again once Hub is migrated to Vercel.
> Update preview url

- data/featured.json
- source/_package_card.erb
Updating the featured packages to reflect some of the dbt-labs repos with higher star counts.
> Updating the featured packages audit-helper -> DPE

- .github/workflows/auto-merge.yml
Although the automerge GHA is configured to not fire until the Vercel build has succeeded (as a required check), it seems to be triggering after the build _begins_ but before the result is reported. 
In lieu of working out _why_, this increases the retry time and count. It takes about 5mins, so 10 attempts with a 1min standdown in between will be plenty. 
We should obviously work out the actual underlying problem, but not right before I go on leave.
> Increase sleep and retries for auto merge

- .github/CODEOWNERS
[Hubcap](https://github.com/dbt-labs/hubcap) identifies new package releases and opens a PR against this repo, which is automatically merged. Because the DX team has responsibility for the repo per the new codeowners file, we are now getting notified on every new package release. We don't need to know! 
Specify the codegenned directories under data/packages/ as having no owner, so that DX doesn't get emailed about things like #3653. (Per https://stackoverflow.com/a/74964396/14007029)
Each DX employee sets up gmail rules to auto-archive the unwanted emails
> Suppress codeowner notifications for package bumps

- data/blocklist.json
- data/featured.json
- data/packages/calogica/dbt_expectations/index.json
Calogica's [dbt-expectations](https://github.com/calogica/dbt-expectations) package is no longer supported. This PR redirects to Metaplane's [dbt-expectations](https://github.com/metaplane/dbt-expectations) package which is supported.
https://github.com/dbt-labs/hub.getdbt.com/pull/3662
> Redirect dbt-expectations from Calogica to Metaplane

- data/blocklist.json
- data/packages/calogica/dbt_date/index.json
Calogica's [dbt-date](https://github.com/calogica/dbt-date) package is no longer supported. This PR redirects to GoDataDriven's [dbt-date](https://github.com/godatadriven/dbt-date) package which is supported.
> Redirect dbt-date from Calogica to GoDataDriven

- data/packages/brooklyn-data/dbt_artifacts/versions/2.9.3.json
Updating this to match the actual package which is as follows:
```
name: "dbt_artifacts"
version: "2.9.3"
config-version: 2
require-dbt-version: [">=1.3.0", "<1.11.0"]
profile: "dbt_artifacts"
```
Link: https://github.com/brooklyn-data/dbt_artifacts/blob/main/dbt_project.yml
> Re-tagged package not picked up (brooklyn-data/dbt_artifacts)

- data/packages/godatadriven/dbt_date/versions/0.16.0.json
https://github.com/godatadriven/dbt-date/pull/25 added an inaccurate require-dbt-version config which was released in v0.16.0. https://github.com/godatadriven/dbt-date/pull/27 fixed that and was released in v0.16.1, but 0.16.0 still exists on the package hub. 
This PR forces the require-dbt-version on hub.getdbt.com to be correct. This means that the package won't be considered for dependency resolution (but it might require a cache invalidation on the S3 side as well - we'll have to check post-merge). 
Options for next steps: 
- Leave the package unchanged and rely on this manual change to exclude it from version resolution. This should be fine unless we ever rebuild the data directory from scratch one day (unlikely). This is my recommendation. 
- Delete this …
> Update dbt_date v0.16.0's minimum dbt version
